### ISSUE TITLE
White-eyed mobs

### ISSUE THREAD

**Issue by xFrah** [Yegiyan/Him#8]
I remember vividly that as a child one of the tales was that herobrine could possess a mob or become a mob and it would have white eyes. It could be a nice feature ahaha.
Maybe herobrine could check if there are any fences with mob inside and become one of them, or check for herds.

![image](https://github.com/user-attachments/assets/a116d876-9696-41f4-b820-7659f60c8e40)

**Comment by Yegiyan** [comment]
Yeah, I remember that too. I can probably add this.
